# EDU AI - Cloud Server (slim deployment edition)
# ===============================================
# Same API contract as proxy_server.py but with ZERO local ML dependencies:
# query embeddings are generated by the Gemini Embedding API instead of a
# local sentence-transformers model, so this server needs only flask+requests
# and fits comfortably inside free hosting tiers (~60MB RAM).
#
# Pairs with vectors_gemini.jsonl (built once by reindex_gemini.py).
# Serves the frontend (../pro1.html) and the API from the SAME origin.
#
# Local test:
#     $env:GOOGLE_API_KEY="..." ; python cloud_server.py   -> http://127.0.0.1:5001
# PythonAnywhere:
#     point the WSGI file at this module's `application` object.

import json
import os
import sys
import time

import requests
from flask import Flask, jsonify, request, send_from_directory


def log(msg):
    """PythonAnywhere's WSGI stdout uses a latin-1 codec, so printing Arabic
    text (e.g. a student question) raises UnicodeEncodeError and kills the
    request with a 500. Log defensively: try a normal print first, then fall
    back to an ascii-escaped version, and never let logging break a request."""
    try:
        print(msg)
    except Exception:
        try:
            print(str(msg).encode("ascii", "backslashreplace").decode("ascii"))
        except Exception:
            pass


APP_DIR = os.path.dirname(os.path.abspath(__file__))
PRO1_HTML = os.path.join(APP_DIR, "..", "pro1.html")
VECTORS_PATH = os.path.join(APP_DIR, "vectors_gemini.jsonl")

GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY", "")
EMBED_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent"
EMBED_MODEL = "models/gemini-embedding-001"

ANTHROPIC_URL = "https://api.anthropic.com/v1/messages"
OPENAI_URL = "https://api.openai.com/v1/chat/completions"
GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"
ANTHROPIC_VERSION = "2023-06-01"

DEFAULT_MODEL = "gemini-flash-latest"
FALLBACK_MODEL = "gemini-flash-lite-latest"  # higher free-tier quota; used when the primary model is rate-limited
GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL = "openai/gpt-oss-120b"           # final safety net: generous free quota from groq.com (no card needed)
MAX_TOKENS = 1000
MAX_ATTEMPTS = 1
TOTAL_TIME_BUDGET = 15  # hard ceiling: if all providers fail, give up after this many seconds
BASE_DELAY = 0.0

log("[cloud] loading vector store ...")
_t0 = time.time()
with open(VECTORS_PATH, "r", encoding="utf-8") as _f:
    VECTORS = [json.loads(_line) for _line in _f if _line.strip()]
log(f"[cloud] loaded {len(VECTORS)} chunk(s) in {time.time() - _t0:.2f}s")
log(f"[cloud] GOOGLE_API_KEY={'set' if GOOGLE_API_KEY else 'MISSING'}")


app = Flask(__name__)


@app.after_request
def add_cors(resp):
    # The hosted frontend shares this origin, so CORS is mostly irrelevant,
    # but keeping permissive headers lets the page also work when opened as
    # a local file pointing at this deployed URL.
    resp.headers["Access-Control-Allow-Origin"] = "*"
    resp.headers["Access-Control-Allow-Headers"] = "Content-Type"
    resp.headers["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
    return resp


def embed_query(text):
    """Embeds a student question via the Gemini Embedding API."""
    resp = requests.post(
        EMBED_URL,
        headers={"Content-Type": "application/json", "x-goog-api-key": GOOGLE_API_KEY},
        json={
            "model": EMBED_MODEL,
            "content": {"parts": [{"text": text}]},
            "taskType": "RETRIEVAL_QUERY",
            "outputDimensionality": 768,
        },
        timeout=10,
    )
    if resp.status_code != 200:
        raise RuntimeError(f"embed failed ({resp.status_code}): {resp.text[:200]}")
    return resp.json()["embedding"]["values"]


def cosine(a, b):
    dot = norm_a = norm_b = 0.0
    for x, y in zip(a, b):
        dot += x * y
        norm_a += x * x
        norm_b += y * y
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / ((norm_a ** 0.5) * (norm_b ** 0.5))


def is_gemini_model(model):
    return (model or "").lower().startswith("gemini")


def is_openai_model(model):
    model = (model or "").lower()
    return model.startswith(("gpt-", "o1", "o3", "o4", "deepseek-"))


def build_payload(body):
    model = body.get("model", DEFAULT_MODEL)
    if is_gemini_model(model):
        contents = []
        for msg in body.get("messages", []):
            role = "model" if msg.get("role") == "assistant" else "user"
            contents.append({"role": role, "parts": [{"text": msg.get("content", "")}]})
        if not contents:
            contents = [{"role": "user", "parts": [{"text": ""}]}]
        return model, {
            "systemInstruction": {"parts": [{"text": body.get("system", "")}]},
            "contents": contents,
            "generationConfig": {"temperature": float(body.get("temperature", 0.7))},
        }, "gemini"
    if is_openai_model(model):
        messages = [{"role": "system", "content": body.get("system", "")}]
        messages += body.get("messages", [])
        return model, {
            "model": model,
            "messages": messages,
            "max_tokens": int(body.get("max_tokens", MAX_TOKENS)),
            "temperature": float(body.get("temperature", 0.7)),
            "frequency_penalty": float(body.get("frequency_penalty", 0.7)),
            "presence_penalty": float(body.get("presence_penalty", 0.7)),
        }, "openai"
    return model, {
        "model": model,
        "max_tokens": int(body.get("max_tokens", MAX_TOKENS)),
        "system": body.get("system", ""),
        "messages": body.get("messages", []),
        "temperature": float(body.get("temperature", 0.7)),
    }, "anthropic"


def do_request(provider, model, payload):
    """Single provider call with tight timeout — never >10s."""
    t0 = time.time()
    if provider == "gemini":
        resp = requests.post(
            GEMINI_BASE.format(model=model),
            json=payload,
            headers={"Content-Type": "application/json", "x-goog-api-key": GOOGLE_API_KEY},
            timeout=10,
        )
        log(f"[api] gemini {model}: {resp.status_code} in {time.time()-t0:.1f}s")
        return resp
    if provider == "openai":
        resp = requests.post(
            OPENAI_URL,
            json=payload,
            headers={"Content-Type": "application/json", "Authorization": f"Bearer {os.environ.get('OPENAI_API_KEY', '')}"},
            timeout=10,
        )
        log(f"[api] openai {model}: {resp.status_code} in {time.time()-t0:.1f}s")
        return resp
    resp = requests.post(
        ANTHROPIC_URL,
        json=payload,
        headers={
            "Content-Type": "application/json",
            "x-api-key": os.environ.get("ANTHROPIC_API_KEY", ""),
            "anthropic-version": ANTHROPIC_VERSION,
        },
        timeout=10,
    )


def extract_text(provider, data):
    if provider == "gemini":
        text = ""
        for cand in data.get("candidates") or []:
            for part in (cand.get("content") or {}).get("parts") or []:
                text += part.get("text", "")
        return text
    if provider == "openai":
        return (data.get("choices") or [{}])[0].get("message", {}).get("content", "")
    return "".join(block.get("text", "") for block in data.get("content", []) if block.get("type") == "text")


def _try_flatten_json_message(text):
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.strip("`")
        if cleaned[:4].lower() == "json":
            cleaned = cleaned[4:]
        cleaned = cleaned.strip()
    if not (cleaned.startswith("{") and cleaned.endswith("}")):
        return None
    try:
        parsed = json.loads(cleaned)
    except (ValueError, TypeError):
        return None
    if isinstance(parsed, dict) and isinstance(parsed.get("message"), str):
        return parsed
    return None


@app.route("/", methods=["GET"])
def index():
    return send_from_directory(os.path.abspath(os.path.join(APP_DIR, "..")), "pro1.html")


@app.route("/api/rag/query", methods=["POST"])
def rag_query():
    t_start = time.time()
    body = request.get_json(silent=True) or {}
    question = (body.get("question") or "").strip()
    log(f"[rag] question={question!r}")
    if not question:
        return jsonify({"chunks": []})
    top_k = int(body.get("top_k", 4))
    try:
        qvec = embed_query(question)
    except Exception as e:
        log(f"[rag] embedding failed: {e}")
        return jsonify({"error": "rag_error", "detail": str(e)}), 502

    scored = [
        {
            "text": r["text"],
            "source": r["source"],
            "page": r.get("page"),
            "chunk_index": r["chunk_index"],
            "score": cosine(qvec, r["embedding"]),
        }
        for r in VECTORS
    ]
    scored.sort(key=lambda x: x["score"], reverse=True)
    chunks = scored[:top_k]
    log(f"[rag] returned {len(chunks)} chunk(s), top score={chunks[0]['score']:.3f}" if chunks else "[rag] empty store")
    log(f"[rag] total request time: {(time.time() - t_start) * 1000:.0f}ms")
    return jsonify({"chunks": chunks})


@app.route("/api/chat", methods=["POST"])
def chat():
    t_start = time.time()
    body = request.get_json(silent=True) or {}
    model, payload, provider = build_payload(body)
    log(f"[chat] provider={provider} model={model} messages={len(body.get('messages') or [])}")

    def time_left():
        return TOTAL_TIME_BUDGET - (time.time() - t_start)

    def try_gemini(m):
        """Single attempt — returns (text, None) on success, (None, (status, detail)) on failure."""
        if time_left() < 1:
            return None, (503, "time_budget_exhausted")
        try:
            resp = do_request("gemini", m, payload)
            data = resp.json()
        except Exception as e:
            log(f"[chat] gemini {m} exception: {e}")
            return None, (502, str(e)[:200])
        if resp.status_code == 200:
            text = extract_text("gemini", data)
            return text, None
        log(f"[chat] gemini {m} failed: {resp.status_code}")
        return None, (resp.status_code, resp.text[:200])

    # ---- Try primary model (single attempt — 429 = quota gone, no point retrying) ----
    text, err = try_gemini(model)
    if text is not None:
        flattened = _try_flatten_json_message(text)
        log(f"[chat] primary ok in {time.time()-t_start:.1f}s")
        return jsonify(flattened or {"text": text})

    # ---- Fallback: flash-lite (higher quota, single attempt) ----
    if is_gemini_model(model) and "lite" not in model.lower():
        text, err2 = try_gemini(FALLBACK_MODEL)
        if text is not None:
            log(f"[chat] flash-lite ok in {time.time()-t_start:.1f}s")
            flattened = _try_flatten_json_message(text)
            return jsonify(flattened or {"text": text})

    # ---- Final safety net: Groq (single attempt, 10s timeout) ----
    groq_key = os.environ.get("GROQ_API_KEY", "")
    if groq_key and time_left() > 1:
        try:
            resp = requests.post(
                GROQ_URL,
                json={
                    "model": GROQ_MODEL,
                    "messages": [{"role": "system", "content": body.get("system", "")}] + body.get("messages", []),
                    "temperature": float(body.get("temperature", 0.7)),
                    "max_tokens": int(body.get("max_tokens", MAX_TOKENS)),
                },
                headers={"Authorization": f"Bearer {groq_key}", "Content-Type": "application/json"},
                timeout=min(10, int(time_left())),
            )
            if resp.status_code == 200:
                data = resp.json()
                text = (data.get("choices") or [{}])[0].get("message", {}).get("content", "")
                flattened = _try_flatten_json_message(text)
                log(f"[chat] groq ok in {time.time()-t_start:.1f}s")
                return jsonify(flattened or {"text": text})
            log(f"[chat] groq failed: {resp.status_code}: {resp.text[:200]}")
        except Exception as e:
            log(f"[chat] groq exception: {e}")

    total_ms = (time.time() - t_start) * 1000
    log(f"[chat] all providers failed in {total_ms:.0f}ms")
    return jsonify({"error": "upstream_error", "detail": "all_providers_exhausted", "ms": int(total_ms)}), 502


# WSGI entry point for PythonAnywhere / gunicorn / uwsgi.
application = app

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=int(os.environ.get("PORT", "5001")), debug=False)
