# Re-indexes the knowledge base with Gemini embeddings (cloud edition)
# =====================================================================
# The local project embeds chunks with a local sentence-transformers model,
# which needs torch (~300MB RAM) — too heavy for free cloud hosting.
# This script keeps every chunk's text/source/page metadata from the existing
# vectors.jsonl and ONLY replaces the embedding vectors with ones generated by
# the Gemini Embedding API (text-embedding-004), so the deployed server never
# needs any local ML libraries at all.
#
# Run ONCE locally (needs internet + GOOGLE_API_KEY):
#     $env:GOOGLE_API_KEY="..."   (PowerShell)
#     python reindex_gemini.py
#
# Output: vectors_gemini.jsonl next to this script → upload it with the server.

import json
import os
import sys
import time

import requests

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE_VECTORS = os.path.join(HERE, "..", "rag", "store", "vectors.jsonl")
OUTPUT_VECTORS = os.path.join(HERE, "vectors_gemini.jsonl")

API_KEY = os.environ.get("GOOGLE_API_KEY", "")
EMBED_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent"
EMBED_MODEL = "models/gemini-embedding-001"
EMBED_DIM = 768          # truncated (Matryoshka) dimensionality — smaller storage, same search quality
PAUSE_SECONDS = 0.15     # stay well inside free-tier rate limits


def embed_text(text, task_type):
    """Embeds one text via the Gemini Embedding API and returns the vector."""
    resp = requests.post(
        EMBED_URL,
        headers={"Content-Type": "application/json", "x-goog-api-key": API_KEY},
        json={
            "model": EMBED_MODEL,
            "content": {"parts": [{"text": text}]},
            "taskType": task_type,  # RETRIEVAL_DOCUMENT for chunks, RETRIEVAL_QUERY for questions
            "outputDimensionality": EMBED_DIM,
        },
        timeout=30,
    )
    if resp.status_code != 200:
        raise RuntimeError(f"embed failed ({resp.status_code}): {resp.text[:200]}")
    return resp.json()["embedding"]["values"]


def main():
    if not API_KEY:
        print("ERROR: GOOGLE_API_KEY is not set in this terminal.")
        print('PowerShell example:  $env:GOOGLE_API_KEY="your_key_here"')
        sys.exit(1)

    with open(SOURCE_VECTORS, "r", encoding="utf-8") as f:
        records = [json.loads(line) for line in f if line.strip()]
    print(f"Loaded {len(records)} chunk(s) from rag/store/vectors.jsonl")

    done = 0
    t0 = time.time()
    with open(OUTPUT_VECTORS, "w", encoding="utf-8") as out:
        for r in records:
            vec = embed_text(r["text"], task_type="RETRIEVAL_DOCUMENT")
            out.write(json.dumps({
                "source": r["source"],
                "page": r.get("page"),
                "chunk_index": r["chunk_index"],
                "text": r["text"],
                "embedding": vec,
            }, ensure_ascii=False) + "\n")
            done += 1
            if done % 25 == 0:
                rate = done / max(time.time() - t0, 0.001)
                print(f"  {done}/{len(records)} embedded ({rate:.1f}/s)")
            time.sleep(PAUSE_SECONDS)

    size_mb = os.path.getsize(OUTPUT_VECTORS) / (1024 * 1024)
    print(f"DONE: {done} chunk(s) -> {OUTPUT_VECTORS} ({size_mb:.1f} MB) in {time.time() - t0:.0f}s")


if __name__ == "__main__":
    main()
